public without sharing class ClienteHandler extends TriggerHandler{
	
	public ClienteHandler () {
		// Code here
	}
    
    public override void beforeInsert(){
		// Code here
	}
	
	public override void beforeDelete(){
		// Code here
	}
    
	public override void beforeUpdate(){
		// Code here
	}
	
	public override void afterInsert(){
		// Code here
	}
	
	public override void afterUpdate(){
		// Code here
	}
}